apiVersion: projectcalico.org/v3
kind: EgressGatewayPolicy
metadata:
  name: "egw-policy"
spec:
  rules:
  - destination:
      cidr: 10.0.0.0/8
    description: "Local: no gateway"
  - destination:
      cidr: 8.8.8.8/32
    description: "Gateway to GoogleDNS"
    gateway:
      namespaceSelector: "projectcalico.org/name == 'tenant0-egw'"
      selector: "k8s-app == 'tenant0-egw'"
