---
apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  labels:
    app: netshoot
spec:
  containers:
  - image: nicolaka/netshoot
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
    name: netshoot
  restartPolicy: Always
